version: '3.4'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: building_mgmt

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  buildingmgmt:
    image: buildingmgmt
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
